syntax = "proto3";

package raft;
option java_outer_classname = "RaftSpec";

message LogEntry {
    int64 term = 1;
    string command = 2;
}

message AppendEntries {
    int64 term = 1;
    string leader_id = 2;
    int64 prev_log_index = 3;
    int64 prev_log_term = 4;
    repeated LogEntry entries = 5;
    int64 leader_commit = 6;
}

message AppendEntriesResponse {
    int64 term = 1;
    bool success = 2;
}

message RequestVote {
    int64 term = 1;
    string candidate_id = 2;
    int64 last_log_index = 3;
    int64 last_log_term = 4;
}

message RequestVoteResponse {
    int64 term = 1;
    bool vote_granted = 2;
}

message SubmitCommand {
    string command = 1;
}

message SubmitCommandResponse {
    bool success = 1;
    string leader_id = 2;
    bool committed = 3;
    string result = 4;
}

service Raft {
    rpc AppendEntriesRPC(AppendEntries) returns (AppendEntriesResponse) {}
    rpc RequestVoteRPC(RequestVote) returns (RequestVoteResponse) {}
    rpc SubmitCommandRPC(SubmitCommand) returns (SubmitCommandResponse) {}
}
